name: weather_aqi_app
description: Weather + AQI pro
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  lottie: ^3.1.0
  flutter_spinkit: ^5.2.0
  fl_chart: ^0.60.0
  google_fonts: ^5.0.0
  flutter_dotenv: ^5.0.2
  geolocator: ^10.0.0
  intl: ^0.18.0

flutter:
  uses-material-design: true
 
  assets:
    - .env